baseURL = "https://davidAlvaBro.github.io/webpage_for_comsum/"
title = "Social Graph of Books"
description = "Doesn't matter"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["August Hertz Bugge", "David Bro Ludvigsen", "Sebastian Nicolai Fabricius Grut"]
    notebook = "https://github.com/davidAlvaBro/comsocsci_final_proj/blob/main/Explainer_notebook.ipynb"
    data = "https://drive.google.com"
    github = "https://github.com/davidAlvaBro/comsocsci_final_proj"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Shelf Network"
        link = "/shelf-network"
    [[params.nav]]
        label = "NLP Network"
        link = "/nlp-network"
    [[params.nav]]
        label = "Findings"
        link = "/findings"